FORMAT: 1A
HOST: http://api.sensor01.net/

# Sensor-RESTFul
Provide RESTFul API service for sensors

# Group Sensor Resources
Access Sensor resources

## Sensor01 [/sensor01{?page,size}]
### Get all sensor data [GET]

+ Parameters
    + page (required, number,`1`)... page `number`
    + size (required, number,`10`)... page `size`

+ Request
    
    + Header
        
            Authorization: Basic YWRtaW46SXZzZzEyMzQ=
            x-api-version: 1.0

+ Response 200 (application/json)

    + Header
        
            ETag: "YWRtaW46SXZzZzEyMzQ="
            cache-control: max-age=600

    + Body
    
            {
                "page":{
                    "number": 1,
                    "size": 10,
                    "totalPages": 20
                },
                "sensors":
                [
                    {
                        "macAddress":"00:0c:cc:56:e3:c2",
                        "mapInfo":{
                            "mapHierarchyString":"RTP-Campus>RTP6P PineView>RTP6P 1st Floor",
                            "floorRefId":"-6047624345759514600",
                            "floorDimension":{
                                "length":198.0,
                                "width":305.8,
                                "height":10.0,
                                "offsetX":0.0,
                                "offsetY":0.0,
                                "unit":"FEET"
                            },
                            "image":{
                                "imageName":"domain_0_1509732892286.jpg",
                                "zoomLevel":6,
                                "width":5100.0,
                                "height":3300.0,
                                "size":5100.0,
                                "maxResolution":32.0,
                                "colorDepth":8
                            }
                        },
                        "mapCoordinate":{
                            "x":83.8547,
                            "y":69.538864,
                            "z":0.0,
                            "unit":"FEET"
                        },
                        "currentlyTracked":true,
                        "confidenceFactor":24.0,
                        "locComputeType":"RSSI",
                        "statistics":{
                            "currentServerTime":"2017-11-29T10:25:13.347-0500",
                            "firstLocatedTime":"1969-12-31T19:00:00.000-0500",
                            "lastLocatedTime":"2017-11-29T10:24:39.419-0500",
                            "maxDetectedRssi":{
                                "apMacAddress":"dc:a5:f4:b8:f9:60",
                                "band":"IEEE_802_11_B",
                                "slot":0,
                                "rssi":-30,
                                "antennaIndex":0,
                                "lastHeardInSeconds":1
                            }
                        },
                        "historyLogReason":null,
                        "geoCoordinate":null,
                        "rawLocation":{
                           "rawX":-999.0,
                           "rawY":-999.0,
                           "unit":"FEET"
                        },
                        "networkStatus":"ACTIVE",
                        "changedOn":1511969079419,
                        "telemetryList":
                        [
                            {
                                "type":"TEMPERATURE",
                                "units":"degrees Celsius",
                                "value":"24.4375",
                                "lastReceivedTime":"2017-11-29T10:24:38.002-0500",
                                "lastReceivedSeqNum":571,
                                "telemetryMeasurementData":{
                                    "measurementData":"TEMPERATURE : com.cisco.mse.model.location.ctx.AesAbstractTelemMeasurement@0 degrees Celsius",
                                    "measurementDataType":"TEMPERATURE",
                                    "bytes":"QcOAAA==",
                                    "lengthInBytes":4
                                }
                            }
                        ],
                        "batteryInfo":{
                            "tolerance":20,
                            "percentRemaining":80,
                            "daysRemaining":48968,
                            "batteryAge":754,
                            "lastReceivedTime":"2017-11-29T10:24:38.002-0500",
                            "lastReceivedSeqNum":571
                        },
                        "vendorData":{
                            "vendorId":3276,
                            "elementId":0,
                            "data":"AAAPAA==",
                            "lastReceivedTime":"2017-11-29T10:24:38.002-0500",
                            "lastReceivedSeqNum":571
                        },
                        "sortedEmergencyList":null,
                        "sortedChokepointList":null,
                        "lastBeaconTime":null,
                        "lastBeaconSequenceNumber":571,
                        "deviceSubtype":null,
                        "bleAttributesList":null,
                        "manufacturer":"Aeroscout Ltd."
                    },
                    {
                        "macAddress":"00:18:8e:40:90:12",
                        "mapInfo":{
                            "mapHierarchyString":"RTP-Campus>RTP6P PineView>RTP6P 1st Floor",
                            "floorRefId":"-6047624345759514600",
                            "floorDimension":{
                                "length":198.0,
                                "width":305.8,
                                "height":10.0,
                                "offsetX":0.0,
                                "offsetY":0.0,
                                "unit":"FEET"
                            },
                            "image":{
                                "imageName":"domain_0_1509732892286.jpg",
                                "zoomLevel":6,
                                "width":5100.0,
                                "height":3300.0,
                                "size":5100.0,
                                "maxResolution":32.0,
                                "colorDepth":8
                            }
                        },
                        "mapCoordinate":{
                            "x":83.225685,
                            "y":69.496544,
                            "z":0.0,
                            "unit":"FEET"
                        },
                        "currentlyTracked":true,
                        "confidenceFactor":16.0,
                        "locComputeType":"RSSI",
                        "statistics":{
                            "currentServerTime":"2017-11-29T10:25:13.348-0500",
                            "firstLocatedTime":"1969-12-31T19:00:00.000-0500",
                            "lastLocatedTime":"2017-11-29T10:24:17.420-0500",
                            "maxDetectedRssi":{
                                "apMacAddress":"dc:a5:f4:b8:f9:60",
                                "band":"IEEE_802_11_B",
                                "slot":0,
                                "rssi":-40,
                                "antennaIndex":0,
                                "lastHeardInSeconds":2
                            }
                        },
                        "historyLogReason":null,
                        "geoCoordinate":null,
                        "rawLocation":{
                            "rawX":-999.0,
                            "rawY":-999.0,
                            "unit":"FEET"
                        },
                        "networkStatus":"ACTIVE",
                        "changedOn":1511969057420,
                        "telemetryList":null,
                        "batteryInfo":{
                            "tolerance":70,
                            "percentRemaining":100,
                            "daysRemaining":0,
                            "batteryAge":0,
                            "lastReceivedTime":"2017-11-29T10:24:47.792-0500",
                            "lastReceivedSeqNum":3544
                        },
                        "vendorData":{
                            "vendorId":6286,
                            "elementId":0,
                            "data":"AAMAAQE=",
                            "lastReceivedTime":"2017-11-29T10:24:47.792-0500",
                            "lastReceivedSeqNum":3544
                        },
                        "sortedEmergencyList":null,
                        "sortedChokepointList":null,
                        "lastBeaconTime":null,
                        "lastBeaconSequenceNumber":3544,
                        "deviceSubtype":null,
                        "bleAttributesList":null,
                        "manufacturer":"Ekahau, Inc."
                    },
                    {
                        "macAddress":"00:18:8e:65:11:20",
                        "mapInfo":{
                            "mapHierarchyString":"RTP-Campus>RTP6P PineView>RTP6P 1st Floor",
                            "floorRefId":"-6047624345759514600",
                            "floorDimension":{
                                "length":198.0,
                                "width":305.8,
                                "height":10.0,
                                "offsetX":0.0,
                                "offsetY":0.0,
                                "unit":"FEET"
                            },
                            "image":{
                                "imageName":"domain_0_1509732892286.jpg",
                                "zoomLevel":6,
                                "width":5100.0,
                                "height":3300.0,
                                "size":5100.0,
                                "maxResolution":32.0,
                                "colorDepth":8
                            }
                        },
                        "mapCoordinate":{
                            "x":81.0517,
                            "y":67.20977,
                            "z":0.0,
                            "unit":"FEET"
                        },
                        "currentlyTracked":true,
                        "confidenceFactor":40.0,
                        "locComputeType":"RSSI",
                        "statistics":{
                            "currentServerTime":"2017-11-29T10:25:13.348-0500",
                            "firstLocatedTime":"1969-12-31T19:00:00.000-0500",
                            "lastLocatedTime":"2017-11-29T10:23:33.420-0500",
                            "maxDetectedRssi":{
                                "apMacAddress":"dc:a5:f4:b8:f9:60",
                                "band":"IEEE_802_11_B",
                                "slot":0,
                                "rssi":-44,
                                "antennaIndex":0,
                                "lastHeardInSeconds":1
                            }
                        },
                        "historyLogReason":null,
                        "geoCoordinate":null,
                        "rawLocation":{
                            "rawX":-999.0,
                            "rawY":-999.0,
                            "unit":"FEET"
                        },
                        "networkStatus":"ACTIVE",
                        "changedOn":1511969013420,
                        "telemetryList":null,
                        "batteryInfo":{
                            "tolerance":70,
                            "percentRemaining":60,
                            "daysRemaining":0,
                            "batteryAge":0,
                            "lastReceivedTime":"2017-11-29T10:23:32.006-0500",
                            "lastReceivedSeqNum":1150
                        },
                        "vendorData":{
                            "vendorId":6286,
                            "elementId":0,
                            "data":"AAIAAgADAAYAATo=",
                            "lastReceivedTime":"2017-11-29T10:23:32.006-0500",
                            "lastReceivedSeqNum":1150
                        },
                        "sortedEmergencyList":null,
                        "sortedChokepointList":null,
                        "lastBeaconTime":null,
                        "lastBeaconSequenceNumber":1150,
                        "deviceSubtype":null,
                        "bleAttributesList":null,
                        "manufacturer":"Ekahau, Inc."
                    }
                ]
            }